import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowLeft, Ban, CheckCircle2, ChevronRight, Database, LayoutDashboard, LogOut, Menu, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, UserRound, Users, X } from 'lucide-react'
import { API_BASE } from './api'
import './admin.css'

type Customer = {id:string;email:string;display_name:string;role:string;active:boolean;created_at:string;last_activity?:string;email_verified?:boolean;license?:{plan:string;expires_at:string;status:string;starts_at?:string}|null;subscription?:{plan?:string;status?:string;currentPeriodStart?:string;currentPeriodEnd?:string}|null}
type Audit = {id:string;kind:string;message:string;actor:string;subject?:string;created_at:string}
type Overview = {total_users:number;active_users:number;new_users:number;pro_users:number;free_users:number;active_subscriptions:number;expired_subscriptions:number;customers:Customer[];audit:Audit[];billing_live:boolean}
type Section = 'overview'|'users'|'subscriptions'|'activity'|'system'

const planOf = (user:Customer) => String(user.subscription?.plan || user.license?.plan || 'FREE').toUpperCase()
const statusOf = (user:Customer) => user.active ? 'ACTIVE' : 'SUSPENDED'
const date = (value?:string) => value ? new Date(value).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}) : '—'
function safeMessage(payload:unknown):string { return payload && typeof payload === 'object' && 'detail' in payload && typeof (payload as {detail:unknown}).detail === 'string' ? (payload as {detail:string}).detail : 'Unable to complete this admin action.' }

export default function AdminPanel({token,onBack}:{token:string;onBack:()=>void}) {
  const [overview,setOverview] = useState<Overview|null>(null); const [section,setSection] = useState<Section>('overview'); const [query,setQuery] = useState(''); const [filter,setFilter] = useState('ALL'); const [page,setPage] = useState(1); const [selected,setSelected] = useState<Customer|null>(null); const [notice,setNotice] = useState<{kind:'success'|'error';text:string}|null>(null); const [busy,setBusy] = useState(false); const [mobileOpen,setMobileOpen] = useState(false); const pageSize = 8
  const request = async <T,>(path:string, options:RequestInit = {}):Promise<T> => { const headers = new Headers(options.headers); headers.set('Authorization',`Bearer ${token}`); if (options.body) headers.set('Content-Type','application/json'); const response = await fetch(`${API_BASE}/v22${path}`,{...options,headers}); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(safeMessage(payload)); return payload as T }
  const refresh = async () => { setBusy(true); try { setOverview(await request<Overview>('/admin/overview')); setNotice(null) } catch (error) { setNotice({kind:'error',text:error instanceof Error ? error.message : 'Unable to load admin data.'}) } finally { setBusy(false) } }
  useEffect(() => { void refresh() }, [])
  const filtered = useMemo(() => (overview?.customers || []).filter(user => { const text = `${user.display_name} ${user.email}`.toLowerCase(); const plan = planOf(user); const status = statusOf(user); return text.includes(query.toLowerCase()) && (filter === 'ALL' || filter === plan || filter === status) }),[overview,query,filter])
  const rows = filtered.slice((page - 1) * pageSize,page * pageSize); const go = (next:Section) => { setSection(next); setMobileOpen(false); setPage(1) }
  const mutate = async (user:Customer, action:'status'|'plan'|'role') => { try { if (action === 'status') { const active = !user.active; if (!window.confirm(`Are you sure you want to ${active ? 'activate' : 'suspend'} this account?`)) return; await request(`/customers/${user.id}/status`,{method:'POST',body:JSON.stringify({active,reason:'Admin Control Center'})}) } else if (action === 'plan') { const nextPlan = (window.prompt('Plan: FREE, PRO, STARTER or ELITE',planOf(user)) || '').trim().toUpperCase(); if (!['FREE','PRO','STARTER','ELITE'].includes(nextPlan) || !window.confirm('Change this user\'s plan?')) return; await request('/subscriptions/activate-demo',{method:'POST',body:JSON.stringify({user_id:user.id,plan:nextPlan === 'FREE' ? 'TRIAL' : nextPlan,days:30})}) } else { const nextRole = user.role === 'OWNER' ? 'CUSTOMER' : 'OWNER'; if (!window.confirm(`Change this user role to ${nextRole}?`)) return; await request(`/admin/users/${user.id}/role`,{method:'PATCH',body:JSON.stringify({role:nextRole})}) } await refresh(); setSelected(null); setNotice({kind:'success',text:'Admin action completed successfully.'}) } catch (error) { setNotice({kind:'error',text:error instanceof Error ? error.message : 'Unable to complete this admin action.'}) } }
  const nav = [['overview','Overview',LayoutDashboard],['users','Users',Users],['subscriptions','Subscriptions',SlidersHorizontal],['activity','Activity',Activity],['system','System',Database]] as const
  return <main className="adminShell"><aside className={`adminSidebar ${mobileOpen ? 'open' : ''}`}><div className="adminBrand"><span>PROTREBOT</span><b>ELITE X</b><small>CONTROL CENTER</small></div><nav>{nav.map(([key,label,Icon]) => <button key={key} className={section === key ? 'active' : ''} onClick={() => go(key)}><Icon/><span>{label}</span></button>)}</nav><div className="adminSidebarFoot"><button onClick={() => go('system')}><Settings/> Settings</button><button onClick={onBack}><LogOut/> Logout</button></div></aside>{mobileOpen && <button className="adminBackdrop" aria-label="Close menu" onClick={() => setMobileOpen(false)}/>}<section className="adminMain"><header className="adminTopbar"><button className="adminMenuButton" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu/></button><div><span>CONTROL CENTER / {section.toUpperCase()}</span><h1>{section === 'overview' ? 'Good afternoon, Admin' : section[0].toUpperCase() + section.slice(1)}</h1><p>{section === 'overview' ? 'Platform overview and account management.' : 'Manage verified platform data and account operations.'}</p></div><div className="adminTopActions"><span className="adminOnline"><i/>SYSTEM ONLINE</span><button onClick={() => void refresh()} disabled={busy} aria-label="Refresh"><RefreshCw className={busy ? 'spin' : ''}/></button><button onClick={onBack} aria-label="Back to dashboard"><ArrowLeft/></button></div></header>{notice && <div className={`adminToast ${notice.kind}`}>{notice.text}</div>}{section === 'overview' && <OverviewSection overview={overview} onUsers={() => go('users')} onSubscriptions={() => go('subscriptions')} />}{section === 'users' && <UsersSection users={rows} count={filtered.length} query={query} filter={filter} page={page} pageSize={pageSize} onQuery={value => {setQuery(value);setPage(1)}} onFilter={value => {setFilter(value);setPage(1)}} onPage={setPage} onSelect={setSelected} onPlan={user => void mutate(user,'plan')} onStatus={user => void mutate(user,'status')} />}{section === 'subscriptions' && <SubscriptionsSection users={overview?.customers || []} onSelect={setSelected} onPlan={user => void mutate(user,'plan')} />}{section === 'activity' && <ActivitySection items={overview?.audit || []} />}{section === 'system' && <SystemSection overview={overview} />}</section>{selected && <UserDrawer user={selected} onClose={() => setSelected(null)} onPlan={() => void mutate(selected,'plan')} onStatus={() => void mutate(selected,'status')} onRole={() => void mutate(selected,'role')} />}</main>
}

function Stat({label,value,detail,accent=false}:{label:string;value:string|number;detail:string;accent?:boolean}) { return <article className={`adminStat ${accent ? 'accent' : ''}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article> }
function OverviewSection({overview,onUsers,onSubscriptions}:{overview:Overview|null;onUsers:()=>void;onSubscriptions:()=>void}) { return <div className="adminContent"><section className="adminStatGrid"><Stat label="Total users" value={overview?.total_users ?? '—'} detail="All registered accounts" accent/><Stat label="Active users" value={overview?.active_users ?? '—'} detail="Currently enabled"/><Stat label="New users" value={overview?.new_users ?? '—'} detail="Last 30 days"/><Stat label="PRO users" value={overview?.pro_users ?? '—'} detail="Current plan"/><Stat label="FREE users" value={overview?.free_users ?? '—'} detail="No paid plan"/><Stat label="Active subscriptions" value={overview?.active_subscriptions ?? '—'} detail="Current access"/><Stat label="Expired" value={overview?.expired_subscriptions ?? '—'} detail="Needs attention"/></section><section className="adminOverviewGrid"><article className="adminPanelCard adminWelcome"><span className="adminKicker">ACCOUNT OPERATIONS</span><h2>Keep the workspace disciplined.</h2><p>Review verified account data, membership status and audit activity from one controlled center.</p><div><button onClick={onUsers}>Manage users <ChevronRight/></button><button className="quiet" onClick={onSubscriptions}>Review subscriptions <ChevronRight/></button></div></article><article className="adminPanelCard adminHealth"><header><div><span className="adminKicker">PLATFORM SIGNAL</span><h2>System overview</h2></div><Database/></header><div className="adminHealthRow"><i className="pending"/><span><b>Runtime health</b><small>Detailed health data is not available in the admin overview response.</small></span></div><div className="adminHealthRow"><i className="ready"/><span><b>Account storage</b><small>{overview ? 'Connected to admin data snapshot' : 'Waiting for data'}</small></span></div></article></section></div> }
function UsersSection({users,count,query,filter,page,pageSize,onQuery,onFilter,onPage,onSelect,onPlan,onStatus}:{users:Customer[];count:number;query:string;filter:string;page:number;pageSize:number;onQuery:(v:string)=>void;onFilter:(v:string)=>void;onPage:(v:number)=>void;onSelect:(u:Customer)=>void;onPlan:(u:Customer)=>void;onStatus:(u:Customer)=>void}) { return <div className="adminContent"><section className="adminPanelCard adminTableCard"><header className="adminSectionTitle"><div><span className="adminKicker">USER MANAGEMENT</span><h2>Users</h2><p>Manage accounts, roles and memberships.</p></div><div className="adminTableFilters"><label><Search/><input value={query} onChange={event => onQuery(event.target.value)} placeholder="Search users..."/></label><select value={filter} onChange={event => onFilter(event.target.value)}><option value="ALL">All users</option><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option><option value="PRO">PRO</option><option value="FREE">FREE</option><option value="ELITE">ELITE</option></select></div></header><div className="adminDataTable"><div className="adminDataHead"><span>User</span><span>Role</span><span>Plan</span><span>Status</span><span>Created</span><span>Actions</span></div>{users.map(user => <div className="adminDataRow" key={user.id}><button className="adminIdentity" onClick={() => onSelect(user)}><span className="adminAvatar"><UserRound/></span><span><b>{user.display_name}</b><small>{user.email}</small></span></button><span className="adminBadge role">{user.role === 'OWNER' ? 'ADMIN' : 'USER'}</span><span className="adminBadge plan">{planOf(user)}</span><span className={`adminStatus ${user.active ? 'active' : 'suspended'}`}><i/>{statusOf(user)}</span><time>{date(user.created_at)}</time><div className="adminRowActions"><button onClick={() => onPlan(user)}>Plan</button><button onClick={() => onStatus(user)} aria-label={user.active ? 'Suspend account' : 'Activate account'}>{user.active ? <Ban/> : <CheckCircle2/>}</button></div></div>)}{!users.length && <div className="adminEmpty"><Users/><b>{query ? 'No users match your search.' : 'No users found.'}</b><span>Verified account data will appear here.</span></div>}</div><footer className="adminPager"><span>{count} users</span><div><button disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><b>{page}</b><button disabled={page * pageSize >= count} onClick={() => onPage(page + 1)}>Next</button></div></footer></section></div> }
function SubscriptionsSection({users,onSelect,onPlan}:{users:Customer[];onSelect:(u:Customer)=>void;onPlan:(u:Customer)=>void}) { const active=users.filter(user => user.subscription?.status === 'active' || user.license?.status === 'ACTIVE'); const expired=users.filter(user => user.license?.expires_at && new Date(user.license.expires_at) < new Date()); return <div className="adminContent"><section className="adminStatGrid"><Stat label="Active" value={active.length} detail="Current access" accent/><Stat label="PRO / ELITE" value={users.filter(user => ['PRO','ELITE'].includes(planOf(user))).length} detail="Paid plan records"/><Stat label="Expired" value={expired.length} detail="Expired license records"/></section><section className="adminPanelCard adminTableCard"><header className="adminSectionTitle"><div><span className="adminKicker">MEMBERSHIP CONTROL</span><h2>Subscriptions</h2><p>Real subscription and license records only.</p></div></header><div className="adminDataTable"><div className="adminDataHead"><span>User</span><span>Plan</span><span>Status</span><span>Start</span><span>Expiry</span><span>Action</span></div>{users.map(user => <div className="adminDataRow subscriptionRow" key={user.id}><button className="adminIdentity" onClick={() => onSelect(user)}><span className="adminAvatar"><UserRound/></span><span><b>{user.display_name}</b><small>{user.email}</small></span></button><span className="adminBadge plan">{planOf(user)}</span><span className="adminStatus active"><i/>{user.subscription?.status || user.license?.status || 'FREE'}</span><time>{date(user.subscription?.currentPeriodStart || user.license?.starts_at)}</time><time>{date(user.subscription?.currentPeriodEnd || user.license?.expires_at)}</time><button className="adminTextAction" onClick={() => onPlan(user)}>Change plan <ChevronRight/></button></div>)}{!users.length && <div className="adminEmpty"><SlidersHorizontal/><b>No subscriptions found.</b><span>Membership records will appear here.</span></div>}</div></section></div> }
function ActivitySection({items}:{items:Audit[]}) { return <div className="adminContent"><section className="adminPanelCard adminActivity"><header className="adminSectionTitle"><div><span className="adminKicker">AUDIT TRAIL</span><h2>Activity</h2><p>Recorded administrative and account events.</p></div><Activity/></header>{items.length ? <div className="adminActivityList">{items.map(item => <article key={item.id}><span className="adminActivityDot"/><div><b>{item.message}</b><small>{date(item.created_at)} · {item.kind} · actor {item.actor}</small></div></article>)}</div> : <div className="adminEmpty"><Activity/><b>Activity history is not available yet.</b><span>No recorded audit events were returned.</span></div>}</section></div> }
function SystemSection({overview}:{overview:Overview|null}) { return <div className="adminContent"><section className="adminPanelCard adminSystem"><header className="adminSectionTitle"><div><span className="adminKicker">SYSTEM</span><h2>System health</h2><p>Only values available from the current admin API are shown.</p></div><Database/></header><div className="adminSystemGrid"><div><span>Admin data</span><b className={overview ? 'available' : ''}><i/> {overview ? 'AVAILABLE' : 'UNAVAILABLE'}</b></div><div><span>Database details</span><b className="muted"><i/> NOT EXPOSED</b></div><div><span>Trading status</span><b className="muted"><i/> NOT EXPOSED</b></div><div><span>Email status</span><b className="muted"><i/> NOT EXPOSED</b></div></div></section></div> }
function UserDrawer({user,onClose,onPlan,onStatus,onRole}:{user:Customer;onClose:()=>void;onPlan:()=>void;onStatus:()=>void;onRole:()=>void}) { return <aside className="adminDrawer"><header><div><span className="adminKicker">USER PROFILE</span><h2>{user.display_name}</h2><p>{user.email}</p></div><button onClick={onClose} aria-label="Close drawer"><X/></button></header><div className="adminDrawerBadges"><span className="adminBadge role">{user.role === 'OWNER' ? 'ADMIN' : 'USER'}</span><span className="adminBadge plan">{planOf(user)}</span><span className={`adminStatus ${user.active ? 'active' : 'suspended'}`}><i/>{statusOf(user)}</span></div><dl><dt>ACCOUNT</dt><dd>Created <b>{date(user.created_at)}</b></dd><dd>Last login <b>{user.last_activity ? date(user.last_activity) : 'Not available'}</b></dd><dd>Email verification <b>{user.email_verified === true ? 'Verified' : 'Not available'}</b></dd><dt>SUBSCRIPTION</dt><dd>Plan <b>{planOf(user)}</b></dd><dd>Start <b>{date(user.subscription?.currentPeriodStart || user.license?.starts_at)}</b></dd><dd>Expiry <b>{date(user.subscription?.currentPeriodEnd || user.license?.expires_at)}</b></dd></dl><div className="adminDrawerActions"><button onClick={onPlan}>Change plan</button><button onClick={onStatus}>{user.active ? 'Suspend account' : 'Activate account'}</button><button onClick={onRole}><ShieldCheck/> Change role</button></div></aside> }
